theme: jekyll-theme-minimal
minimal_mistakes_skin: "contrast"
title: Jay Ballesteros-Cobi√°n
description: 
markdown: kramdown
plugins:
  - jekyll-multiple-languages-plugin
  - jemoji
show_downloads: false
github:
  is_project_page: true
languages: ["sp", "en"]